[platformio]
default_envs = gate
src_dir = gate/src
include_dir = shared/include

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
  -std=gnu++17
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
  ${sysenv.EXTRA_BUILD_FLAGS}

[env:gate]
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
lib_deps =
  adafruit/Adafruit PN532 @ ^1.2.2
  adafruit/Adafruit BusIO @ ^1.14.1
  bblanchon/ArduinoJson @ ^7.0.0
build_src_filter =
  +<*>
  +<../../shared/src/*>
